# Generated by Django 3.1.2 on 2020-10-05 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burgers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customburger',
            old_name='seller',
            new_name='creator',
        ),
    ]
