# Generated by Django 3.1.2 on 2020-10-06 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burgers', '0003_auto_20201006_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customburger',
            name='selectBox',
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.DeleteModel(
            name='FeatureCategory',
        ),
    ]
