# Generated by Django 3.1.2 on 2020-10-06 08:55

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('burgers', '0004_auto_20201006_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='customburger',
            name='selectBox',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, '1'), (2, '2')], default='1', max_length=3),
            preserve_default=False,
        ),
    ]
