# Generated by Django 3.1.2 on 2020-10-06 09:09

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('burgers', '0005_customburger_selectbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customburger',
            name='selectBox',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Pork'), (2, 'Beef'), (3, 'Nugget'), (4, 'Grass'), (5, 'URF')], max_length=9),
        ),
    ]
