# Generated by Django 3.1.2 on 2020-10-06 09:16

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('burgers', '0006_auto_20201006_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customburger',
            old_name='selectBox',
            new_name='meats',
        ),
        migrations.AddField(
            model_name='customburger',
            name='buns',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Plain'), (2, 'Sesame seed'), (3, 'Coarse')], default='1', max_length=5),
            preserve_default=False,
        ),
    ]
