# Generated by Django 3.1.2 on 2020-10-06 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burgers', '0007_auto_20201006_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customburger',
            name='buns',
        ),
        migrations.RemoveField(
            model_name='customburger',
            name='info',
        ),
    ]
