# Generated by Django 3.1.2 on 2020-10-06 09:35

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('burgers', '0008_auto_20201006_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='customburger',
            name='buns',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Plain'), (2, 'Sesame seed'), (3, 'Coarse')], default='1', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customburger',
            name='condiments',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(64, 'Tomato'), (65, 'Cucumber'), (66, 'Onion'), (67, 'Bacon'), (68, 'Egg'), (69, 'Ketchup'), (70, 'Burger sauce'), (71, 'Pickles')], default='1', max_length=23),
            preserve_default=False,
        ),
    ]
