# Generated by Django 3.1.2 on 2020-10-09 07:47

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('burgers', '0009_auto_20201006_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='customburger',
            name='salads',
            field=multiselectfield.db.fields.MultiSelectField(choices=[], default='1', max_length=200),
            preserve_default=False,
        ),
    ]
