# Generated by Django 3.1.2 on 2020-10-12 12:43

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('burgers', '0011_auto_20201009_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customburger',
            name='condiments',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Bacon'), (2, 'Guacamole'), (3, 'Mushrooms'), (4, 'Fried egg'), (5, 'Sausage party'), (6, 'Cheddar cheese'), (7, 'American cheese'), (8, 'Swiss cheese')], max_length=15),
        ),
        migrations.AlterField(
            model_name='customburger',
            name='salads',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Mixed greens'), (2, 'Tomatos'), (3, 'Jalapenos'), (4, 'Pepperoncinis'), (5, 'Red onions'), (6, 'Pickles'), (7, 'Cucumbers'), (8, 'Carrot sticks')], max_length=15),
        ),
    ]
