# Generated by Django 3.1.2 on 2020-10-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burgers', '0012_auto_20201012_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customburger',
            name='image',
            field=models.ImageField(blank=True, default='default-burger.png', upload_to='burger_pics/'),
        ),
    ]
