# Generated by Django 3.1.2 on 2020-10-15 11:20

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('burgers', '0014_auto_20201012_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='customburger',
            name='cheeses',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Grilled cheese'), (2, 'American cheese'), (3, 'Cheddar cheese'), (4, 'Gorgonzola cheese'), (5, 'Mozzarella'), (6, 'Parmesan'), (7, 'Gouda'), (8, 'Swiss cheese'), (9, 'Emmentaler'), (10, 'Brie'), (11, 'Camembert'), (12, 'Gruyère cheese'), (13, 'Feta'), (14, 'Monterey Jack')], max_length=32),
        ),
        migrations.AlterField(
            model_name='customburger',
            name='condiments',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Bacon'), (2, 'Guacamole'), (3, 'Mushrooms'), (4, 'Fried egg'), (5, 'Sausage party'), (9, 'ketchup'), (10, 'remolade'), (11, 'burger dressing'), (12, 'Sriracha Butter'), (13, 'Tzatziki'), (14, 'Bolognese'), (15, 'Spicy Mayo'), (16, 'Hash Browns'), (17, 'Buffalo Sauce'), (18, 'Glazed Onions'), (19, 'Truffle Butter'), (20, 'Teriyaki')], max_length=44),
        ),
        migrations.AlterField(
            model_name='customburger',
            name='meats',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(5, 'cow'), (6, 'pig'), (1, 'vegan'), (7, 'walrus'), (8, 'chicken')], max_length=9),
        ),
        migrations.AlterField(
            model_name='customburger',
            name='salads',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Mixed greens'), (2, 'Tomatos'), (3, 'Jalapenos'), (4, 'Pepperoncinis'), (5, 'Red onions'), (6, 'Pickles'), (7, 'Cucumbers'), (8, 'Carrot strings')], max_length=15),
        ),
    ]
